name: CI

on:
  push:
    branches: [ ci-update ]
  pull_request:
    branches: [ ci-update ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Build on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        echo "This runs on Windows"
    - name: Build on macOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        echo "This runs on macOS"
    - name: Build on Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        echo "This runs on Ubuntu"
