name: Windows

on: [push, pull_request]

jobs:
  build:
    name: Build (Visual Studio)
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Prepare build
      run: .\ci-build.ps1
    - name: Run build
      run: cmake --build .\build\ --config RelWithDebInfo --parallel
    - name: Prepare artifact
      run: .\ci-artifact.ps1
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Odamex-Win-x64
        path: 'build/artifact/*'
  build-x32:
    name: Build (Visual Studio, 32-bit)
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Prepare build
      run: .\ci-build-x32.ps1
    - name: Run build
      run: cmake --build .\build-x32\ --config RelWithDebInfo --parallel
    - name: Prepare artifact
      run: .\ci-artifact-x32.ps1
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Odamex-Win-x32
        path: 'build-x32/artifact/*'
  build-mingw:
    name: Build (MinGW)
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install packages
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install ninja
    - name: Prepare build
      run: .\ci-build-mingw.ps1
    - name: Run build
      run: cmake --build .\build-gcc\
